### ISSUE TITLE
Corrigir: Em telas menores que 1555px o bg esta com uma linha branca. 

### ISSUE THREAD

**Issue by uriasvitor** [tatianelima572/Projeto-Nature#6]
![image](https://github.com/tatianelima572/Projeto-Nature/assets/81401104/440dacae-ddd0-46e9-b890-93b38c0dc23e)

Sugestão: Tentar utilizar a propriedade Height:100% no html para o bg pegar a tela inteira.

**Comment by tatianelima572** [comment]
ok

**Comment by uriasvitor** [comment]
![image](https://github.com/tatianelima572/Projeto-Nature/assets/81401104/19b48caf-c922-4abd-916a-4d4c1a5b7412)
Continua o mesmo bug porém em menor escala.
